using System;

namespace TransactionApi.DTOs
{
    public class PaymentCreateRequest
    {
        public Guid? RequestId { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; } = "USD";
        // createdAt and reference are generated by server
    }
}
